fix(api): removed npmrc

diff --git a/.github/workflows/deploy-paperlesspaper-api.yml b/.github/workflows/deploy-paperlesspaper-api.yml
--- a/.github/workflows/deploy-paperlesspaper-api.yml
+++ b/.github/workflows/deploy-paperlesspaper-api.yml
@@ -26,7 +26,7 @@ jobs:
     runs-on: ubuntu-latest
     environment: production
     env:
-      NPMRC_CONTENT: ${{ secrets.NPMRC_CONTENT }}
+#      NPMRC_CONTENT: ${{ secrets.NPMRC_CONTENT }}
 
     steps:
       - name: Checkout
@@ -38,13 +38,13 @@ jobs:
           node-version: 24
           cache: yarn
 
-      - name: Configure npmrc from secret
-        run: |
-          if [ -z "${NPMRC_CONTENT}" ]; then
-            echo "NPMRC_CONTENT is missing"
-            exit 1
-          fi
-          printf "%s\n" "${NPMRC_CONTENT}" > .npmrc
+#      - name: Configure npmrc from secret
+#        run: |
+#          if [ -z "${NPMRC_CONTENT}" ]; then
+#            echo "NPMRC_CONTENT is missing"
+#            exit 1
+#          fi
+#          printf "%s\n" "${NPMRC_CONTENT}" > .npmrc
 
       - name: Install dependencies
         run: yarn install --frozen-lockfile
