fear(app): switched to automated codesigning

diff --git a/.github/workflows/deploy-paperlesspaper-api.yml b/.github/workflows/deploy-paperlesspaper-api.yml
--- a/.github/workflows/deploy-paperlesspaper-api.yml
+++ b/.github/workflows/deploy-paperlesspaper-api.yml
@@ -32,6 +32,17 @@ jobs:
       - name: Setup Flyctl
         uses: superfly/flyctl-actions/setup-flyctl@master
 
+      - name: Restore Firebase Admin SDK key
+        run: |
+          if [ -z "${FIREBASE_ADMINSDK_JSON}" ]; then
+            echo "FIREBASE_ADMINSDK_JSON is missing"
+            exit 1
+          fi
+          printf "%s" "${FIREBASE_ADMINSDK_JSON}" > memo-2e24c-firebase-adminsdk-tjkbf-68c91d96da.json
+        working-directory: packages/paperlesspaper-api
+        env:
+          FIREBASE_ADMINSDK_JSON: ${{ secrets.FIREBASE_ADMINSDK_JSON }}
+
       - name: Deploy to Fly.io
         run: flyctl deploy --remote-only --config fly.toml
         working-directory: packages/paperlesspaper-api
